In [2]:
import sys
import numpy as np

***

# Arrays basicos de Numpy

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=np.array([1,2,3,4])

In [5]:
b=np.array([0,.5,1,1.5,2])

In [6]:
a[0]

1

In [7]:
a[1]

2

In [8]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1:3]

array([2, 3])

In [13]:
a[1:-2]

array([2])

***

# Dimensiones y formas

In [14]:
A=np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
A.shape #2 filas y 3 columnas

(2, 3)

In [16]:
A[1] #devuelve la fila

array([4, 5, 6])

In [17]:
A[1,0] #elemento de la primera columna segunda fila

4

In [18]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [19]:
print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [22]:
a=np.arange(5)
a+20
print(a)

[0 1 2 3 4]
